# Generated by Django 5.0.1 on 2024-01-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imags/')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mijozlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imags/')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Service',
            new_name='Showcase',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='facility',
            new_name='feature',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='image',
            new_name='icon',
        ),
        migrations.AddField(
            model_name='product',
            name='is_worldwide',
            field=models.BooleanField(default=False),
        ),
    ]
