# Generated by Django 5.0.1 on 2024-01-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_features_member_mijozlar_solutions_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solutions',
            new_name='Solution',
        ),
    ]
