# Generated by Django 5.0.1 on 2024-01-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_solutions_solution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mijozlar',
            new_name='Client',
        ),
    ]
