# Generated by Django 5.0.1 on 2024-01-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_mijozlar_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcase',
            name='description',
        ),
    ]
