# Generated by Django 5.0.1 on 2024-01-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_showcase_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
