# Generated by Django 5.0.1 on 2024-01-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_features_delete_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Showcase',
        ),
    ]
